defaults:
  - args: default
  - batch: default
  - elements: default
  - nuclei: Ar36

shared_path: /project/def-holt/shared
project_path: /project/rrg-holt/k239nguy

num_threads: 48
bin: ${project_path}/bin/imsrg++
email: k239nguy@uwaterloo.ca
